name: sqlite_goods_api
description: A Flutter implementation of the GoodsApi that uses sqlite.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  goods_api:
    path: ../goods_api
  rxdart: ^0.27.5
  sqflite: ^2.2.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
