name: sqlite_todos_api
description: A Flutter implementation of the TodosApi that uses sqlite.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+2
  todos_api:
    path: ../todos_api
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
